apiVersion: v1
kind: Template
metadata:
  name: odh-tensorflow-serving-knative
  annotations:
    description: "Template to serve models using tensorflow and knative"
    openshift.io/display-name: "Tensorflow Serving (knative)"
    iconClass: "icon-python"
    tags: "opendatahub,tensorflow"
    openshift.io/provider-display-name: "Open Data Hub"
  labels:
    template: odh-tensorlow-serving-knative
objects:
- apiVersion: serving.knative.dev/v1alpha1
  kind: Service
  metadata:
    name: ohd-tensorflow-serving-knative-${APP_NAME}
  spec:
    runLatest:
      configuration:
        revisionTemplate:
          metadata:
            annotations:
              # Target 10 in-flight-requests per pod.
              autoscaling.knative.dev/target: "${SCALE_FACTOR}"
          spec:
            container:
              image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/odh-tensorflow-serving:latest
              env:
              - name: INPUT_MODEL_LOCATION
                value: ${INPUT_MODEL_LOCATION}
              - name: MODEL_NAME
                value: ${MODEL_NAME}
              - name: S3_ENDPOINT_URL
                valueFrom:
                  secretKeyRef:
                    name: odh-config
                    key: s3_endpoint_url
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: odh-config
                    key: access_key
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: odh-config
                    key: key_id
              resources:
                limits:
                  memory: ${MEMORY}
                  cpu: ${CPU}
parameters:
- name: APP_NAME
  description: Short name of your application (to be used in OpenShift artifact names)
  value: demo
  required: true
- name: INPUT_MODEL_LOCATION
  description: "Location where the resulting model will be stored"
  required: true
  value: s3://MY-BUCKET/model-out/
- name: MODEL_NAME
  description: "Name of the model"
  value: mnist
- name: MEMORY
  description: Memory limit to be assigned to the job
  value: 1Gi
  required: true
- name: CPU
  description: Limit for number of cores to assign to the job
  value: "1"
  required: true
- description: Number of requests served by a single instance/pod
  name: SCALE_FACTOR
  value: "1"
- description: Namespace name the service is supposed to run in (probably current namespace)
  name: NAMESPACE
  value: myproject